#PBS -q research
#PBS -l nodes=8:sixcore
#PBS -l walltime=00:08:00
#PBS -N time_summa

# David S. Noble, Jr.
# CSE 6230
# Project 1

export OMPI_MCA_mpi_yield_when_idle=0
cd $PBS_O_WORKDIR

date
hostname
echo $PWD
cat $PBS_NODEFILE
echo -e "\n\n"

RESULTS=../Results
TRIALS=25
SIZE=256

#NAIVE test
PROCS=64
PROC_X
PROC_Y
mpirun --hostfile $PBS_NODEFILE -np $PROCS ./time_summa -m $SIZE -n $SIZE \
	-k $SIZE -x $PROC_X -y $PROC_Y -b 1--trials $TRIALS --naive

#OPENMP and MKL tests
PROCS=8
THREADS=8
#OPENMP
mpirun --hostfile $PBS_NODEFILE -np $PROCS ./time_summa -m $SIZE -n $SIZE \
	-k $SIZE -x $PROCS -y THREADS -b 1 --trials $TRIALS --openmp $THREADS
#MKL
mpirun --hostfile $PBS_NODEFILE -np $PROCS ./time_summa -m $SIZE -n $SIZE \
	-k $SIZE -x $PROCS -y THREADS -b 1 --trials $TRIALS --mkl $THREADS

# eof
