#PBS -q class_long
#PBS -l nodes=1
#PBS -l walltime=6:00:00
#PBS -N scaling_exps

# David S. Noble, Jr.
# CSE 6230
# Project 1

cd $PBS_O_WORKDIR

date
hostname
echo $PWD
cat $PBS_NODEFILE

TRIALS=5

#Strong Scaling Experiments
RESULTS=./Results/Strong_Scaling
OFILES=$RESULTS/SN
for SIZE in 384 768 1536 3072
do
	OFILE=${OFILES}_MM_OPENMP.csv
	for TPP in 1 2 4 8 12 16 24
	do
		date
		mpirun --hostfile $PBS_NODEFILE -np 1 ./time_mm -m $SIZE -n $SIZE -k $SIZE --trials $TRIALS --openmp $TPP >> $OFILE
	done

	OFILE=${OFILES}_MM_MKL.csv
	for TPP in 1 2 4 8 12 16 24
	do
		date
		mpirun --hostfile $PBS_NODEFILE -np 1 ./time_mm -m $SIZE -n $SIZE -k $SIZE --trials $TRIALS --mkl $TPP >> $OFILE
	done
done

#Weak Scaling Experiments
RESULTS=./Results/Weak_Scaling
OFILES=$RESULTS/SN
for SIZE in 384 768 1536 3072
do
	OFILE=${OFILES}_MM_OPENMP.csv
	for TPP in 1 2 3 4 6 8 12
	do
		KSIZE=$(($SIZE * TPP))
		date
		mpirun --hostfile $PBS_NODEFILE -np 1 ./time_mm -m $SIZE -n $SIZE -k $KSIZE --trials $TRIALS --openmp $TPP >> $OFILE
	done

	OFILE=${OFILES}_MM_MKL.csv
	for TPP in 1 2 3 4 6 8 12
	do
		KSIZE=$(($SIZE * TPP))
		date
		mpirun --hostfile $PBS_NODEFILE -np 1 ./time_mm -m $SIZE -n $SIZE -k $KSIZE --trials $TRIALS --mkl $TPP >> $OFILE
	done
done

#Odd Size Experiments
RESULTS=./Results/Odd_Sizes
OFILES=$RESULTS/SN
for MSIZE in 256 512 1024 2048
do
	for NSIZE in 256 512 1024 2048
	do
		for KSIZE in 256 512 1024 2048
		do
			OFILE=${OFILES}_MM_OPENMP.csv
			for TPP in 1 2 4 8
			do
				date
				mpirun --hostfile $PBS_NODEFILE -np 1 ./time_mm -m $MSIZE -n $NSIZE -k $KSIZE --trials $TRIALS --openmp $TPP >> $OFILE
			done

			OFILE=${OFILES}_MM_MKL.csv
			for TPP in 1 2 4 8
			do
				date
				mpirun --hostfile $PBS_NODEFILE -np 1 ./time_mm -m $MSIZE -n $NSIZE -k $KSIZE --trials $TRIALS --mkl $TPP >> $OFILE
			done
		done
	done
done

echo "FINISHED!!!"
date
# eof
