#PBS -q class
#PBS -l nodes=1
#PBS -l walltime=00:20:00
#PBS -N time_mm

export OMPI_MCA_mpi_yield_when_idle=0
cd $PBS_O_WORKDIR

date
hostname
echo $PWD
cat $PBS_NODEFILE
echo -e "\n\n"

echo "Running Naive"
./time_mm --naive -m 512 -n 512 -k 512 --trials 5
echo "Running MKL"
./time_mm --mkl 1-m 512 -n 512 -k 512 --trials 5
echo "Running OpenMP"
./time_mm --openmp 1 -m 512 -n 512 -k 512 --trials 5
echo "Running OpenMP with cache blocking"
./time_mm --openmp 1 --cbl --bm 32 --bn 32 --bk 32 -m 512 -n 512 -k 512 --trials 5
echo "Running OpenMP with cache blocking and copy optimization"
./time_mm --openmp 1 --cbl --cop --bm 32 --bn 32 --bk 32 -m 512 -n 512 -k 512 --trials 5

# eof
