#PBS -q class
#PBS -l nodes=1:sixcore
#PBS -l walltime=01:00:00
#PBS -N Proj1

export OMPI_MCA_mpi_yield_when_idle=0
cd $PBS_O_WORKDIR

date
hostname
echo $PWD
cat $PBS_NODEFILE
echo -e "\n\n"

M=256
N=256
K=256
T=25

#Run naive implementation on single node
for NUM_PROCS in {1..24}
do
	mpirun --hostfile $PBS_NODEFILE -np $NUM_PROCS ../time_summa -m $M -n $N -k $K -x 8 -y 8 -b 1 -t $T --naive
done

#Run openmp implementation on single node
export OMP_SCHEDULE="dynamic,1"
for OMP_NUM_THREADS in {1..24}
do
	export OMP_NUM_THREADS
	mpirun --hostfile $PBS_NODEFILE -np 1 ../time_mm -m $M -n $N -k $K -t $T --openmp
done

#Run mkl implementation on single node
export OMP_SCHEDULE="dynamic,1"
for OMP_NUM_THREADS in {1..24}
do
	export OMP_NUM_THREADS
	mpirun --hostfile $PBS_NODEFILE -np 1 ../time_mm -m $M -n $N -k $K -t $T --mkl
done

# eof
